### ISSUE TITLE
Add GraphQL support to Node backend

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-deployable-node-backend#12]
We'd like to make it easy for people to spin up a new application with GraphQL support.

Probably using https://www.apollographql.com/ which is very well supported.

There should be some example code we can probably reuse in https://github.com/commitdev/graphql-nodejs-boilerplate

See also similar support in the Go backend. The example schemas of these two projects must be the same.
zero-deployable-backend#51

Keep in mind that we will want to support multiple API types including both GraphQL and generating the API using OpenAPI/Swagger. Try to implement this in such a way that we can turn it off / swap between different API types based on user choice.

**Comment by larrylin17** [comment]
Thanks Bill. I am going to reuse boilerplate.

**Comment by larrylin17** [comment]
The boilerplate code seems to come from aplllographql.com as well. However, it is a little out of date. Using https://www.apollographql.com/ should be a better choice.
